### ISSUE TITLE
Problem in Nextcloud 13

### ISSUE THREAD

**Issue by martinikh** [nextcloud/loginviapost#8]
The new version of Nexcloud 13 does not work.
It reports internal server error.

It says:
Internal server error.
The server could not complete your request.

**Comment by tomtomas99911** [comment]
Is there any progress please?

**Comment by alexisrosano89** [comment]
Same problem here!

**Comment by martinikh** [comment]
Thank you, the problem is resolved! :-)
Replace the code in the file with this script:

`<?php
/**
 * @copyright Copyright (c) 2017 Lukas Reschke <lukas@statuscode.ch>
 *
 * @license GNU AGPL version 3 or any later version
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

namespace OCA\LoginViaPost\Controller;

use OC\Authentication\TwoFactorAuth\Manager;
use OCA\LoginViaPost\Request;
use OCP\AppFramework\Controller;
use OCP\AppFramework\Http\RedirectResponse;
use OCP\IConfig;
use OCP\ILogger;
use OCP\IRequest;
use OCP\ISession;
use OCP\IURLGenerator;
use OCP\IUserManager;
use OCP\IUserSession;
use OCP\Security\ISecureRandom;

class LoginController extends Controller {
	/** @var IURLGenerator */
	private $urlGenerator;
	/** @var IUserSession */
	private $userSession;
	/** @var IUserManager */
	private $userManager;
	/** @var IConfig */
	private $config;
	/** @var ISession */
	private $session;
	/** @var ILogger */
	private $logger;
	/** @var Manager */
	private $twoFactorAuthManager;
  /** @var Defaults */
  private $defaults;

	public function __construct($appName,
								IRequest $request,
								IURLGenerator $urlGenerator,
								IUserSession $userSession,
								IUserManager $userManager,
								IConfig $config,
								ISession $session,
								ILogger $logger,
								Manager $twoFactorAuthManager) {
		parent::__construct($appName, $request);
		$this->urlGenerator = $urlGenerator;
		$this->userSession = $userSession;
		$this->userManager = $userManager;
		$this->config = $config;
		$this->session = $session;
		$this->logger = $logger;
		$this->twoFactorAuthManager = $twoFactorAuthManager;
    $this->defaults = new \OCP\Defaults();
	}

	private function getMockedRequest() {
		return new Request(
			[
				'get' => $_GET,
				'post' => $_POST,
				'files' => $_FILES,
				'server' => $_SERVER,
				'env' => $_ENV,
				'cookies' => $_COOKIE,
				'method' => (isset($_SERVER) && isset($_SERVER['REQUEST_METHOD']))
					? $_SERVER['REQUEST_METHOD']
					: null,
			],
			null,
			$this->config
		);
	}

	/**
	 * @PublicPage
	 * @NoCSRFRequired
	 * @BruteForceProtection(action=login)
	 * @UseSession
	 *
	 * @param string $username
	 * @param string $password
	 * @return RedirectResponse
	 */
	public function login($username, $password) {
		$class = new \ReflectionClass(\OC\Core\Controller\LoginController::class);
		$parameters = $class->getConstructor()->getParameters();

		/** @var \OC\Core\Controller\LoginController $loginController */
        if(\OCP\Util::getVersion()[0] >= 13) {
            if($parameters[8]->getName() === 'throttler') {
                $loginController = new \OC\Core\Controller\LoginController(
                    'core',
                    $this->getMockedRequest(),
                    $this->userManager,
                    $this->config,
                    $this->session,
                    $this->userSession,
                    $this->urlGenerator,
                    $this->twoFactorAuthManager,
                    $this->defaults,
                    \OC::$server->getBruteForceThrottler()
                );
            } else {
                $loginController = new \OC\Core\Controller\LoginController(
                'core',
                    $this->getMockedRequest(),
                    $this->userManager,
                    $this->config,
                    $this->session,
                    $this->userSession,
                    $this->urlGenerator,
                    $this->logger,
                    $this->twoFactorAuthManager,
                    $this->defaults
                );
            }
        } else {
            if($parameters[8]->getName() === 'throttler') {
                $loginController = new \OC\Core\Controller\LoginController(
                    'core',
                    $this->getMockedRequest(),
                    $this->userManager,
                    $this->config,
                    $this->session,
                    $this->userSession,
                    $this->urlGenerator,
                    $this->twoFactorAuthManager,
                    \OC::$server->getBruteForceThrottler()
                );
            } else {
                $loginController = new \OC\Core\Controller\LoginController(
                'core',
                    $this->getMockedRequest(),
                    $this->userManager,
                    $this->config,
                    $this->session,
                    $this->userSession,
                    $this->urlGenerator,
                    $this->logger,
                    $this->twoFactorAuthManager
                );
            }
        }

		return $loginController->tryLogin($username, $password, '');
	}
}
`

**Comment by alexisrosano89** [comment]
This works for 13.0.4???

**Comment by martinikh** [comment]
Yes, it works. I'm running this plugin with version 13.0.4

S pozdravem
Ing. Martin Procházka

[cid:image001.png@01D407B8.433DAF80]
Masarykova 197, Kutná Hora, 284 01, IČ 61924059, telefon +420 725 974 167
GPS 49.9529653N, 15.2747578E

**Comment by alexisrosano89** [comment]
Thanks for your reply. 

In my local environment it's working okey. But in other environment (other server, for deployment in an specifica domain and url) I'm getting an HTTP 405 Method not allowed.

**Comment by alexisrosano89** [comment]
Hey!

I have found that I'm getting an HTTP 405 cause a cookie called SameSiteCookieStrict. If I erase that cookie, I can login via post.

Exists any workarround for this?

I'm working in localhost, and trying to POST to a domain in another server.

Regards.

**Comment by alexisrosano89** [comment]
@LukasReschke Hello Lukas! How are you? Do you know something about that??

Regards!

**Comment by yrammos** [comment]
Likewise, eagerly hoping to see this resolved.
